### ISSUE TITLE
[ETC] pull requests 한글 템플릿 추가 필요

### ISSUE THREAD

**Issue by LukeHan1128** [Info-Share/info-welding-quality-inspection#11]
1. 이슈 명 (Issue name)
한글 템플릿 추가 필요

2. 이슈 설명 (Issue Description)
이번에 추가된 pull requests 템플릿이 영어로 되어 있습니다.
한국어 사용자들의 사용 편의성을 위해 한글을 추가할 필요가 있을것 같습니다.

**Comment by leeahakwoo** [comment]
해당 템플릿 현재 초안이고 한글화 및 템플릿 상 내용 수정하도록 하겠습니다.

**Comment by leeahakwoo** [comment]
PR 템플릿 내 한글 추가하였습니다.  이슈 클로징하도록하겠습니다.
