### ISSUE TITLE
[ETC] 브랜치 관련 

### ISSUE THREAD

**Issue by leeahakwoo** [Info-Share/info-welding-quality-inspection#12]
1. 이슈 명 (Issue name)
 마스터 브랜치 외 타 브랜치 관련 
2. 이슈 설명 (Issue Description)
 이슈 템플릿을 수정 중 잘못으로 제 이름으로 브랜치가 만들어졌습니다. 
 제 이름으로 만들어진 브랜치에 대해 삭제가 가능한지요?

**Comment by LukeHan1128** [comment]
@leeahakwoo 
예 가능합니다.
메인 페이지 상단에 보시면 branches 라는 탭이 있습니다. (현재 3 branches 로 표기되는 메뉴입니다.)
해당 메뉴에서 들어가시면 branche 관리가 가능합니다.

확인해 보시고 진행이 어려우신 경우 삭제할 branche를 남겨주시면 저희측에서 제거하도록 하겠습니다.
삭제가 완료되면 해당 이슈를 close 처리 하도록 하겠습니다.

**Comment by LukeHan1128** [comment]
마스터 브랜치 이외의 브랜치를 확인할 수 없어 해당 이슈를 종료합니다.
