### ISSUE TITLE
License에 대한 확정 요청 건 

### ISSUE THREAD

**Issue by leeahakwoo** [Info-Share/info-welding-quality-inspection#2]
본 프로젝트의 공개 SW 라이센스에 대한 확정과 기반 문서 업로드 요청드립니다.

**Comment by LukeHan1128** [comment]
@leeahakwoo 
라이선스 정보를 추가하였습니다.
[https://github.com/Info-Share/info-welding-quality-inspection/blob/master/LICENSE](url)
