### ISSUE TITLE
[ETC] 프로젝트 활성화를 위한 사이트 연동

### ISSUE THREAD

**Issue by LukeHan1128** [Info-Share/info-welding-quality-inspection#7]
레이저 비전 카메라를 이용한 영상분석 기반의 용접품질 검사 시스템 프로젝트 활성화를 위해 사이트 링크를 추가하는 것이 좋을 것 같습니다.

**Comment by LukeHan1128** [comment]
프로젝트 관련 링크 추가하였습니다. #8

**Comment by leeahakwoo** [comment]
고생하셨습니다. 감사합니다. ^^
